app/assets/assets/locales/en/videoDebate.json
app/assets/assets/locales/fr/videoDebate.json
app/components/Comments/CommentDisplay.jsx
app/components/Comments/CommentForm.jsx
app/styles/_components/comments.sass

Show replied to comment above textbox

---

app/assets/assets/locales/en/videoDebate.json
app/assets/assets/locales/fr/videoDebate.json
app/components/Comments/CommentForm.jsx
app/components/Statements/Statement.jsx
app/components/Statements/StatementForm.jsx
app/components/Statements/StatementsList.jsx
app/components/VideoDebate/ActionBubbleMenu.jsx
app/components/VideoDebate/ColumnDebate.jsx
app/components/VideoDebate/ColumnVideo.jsx
app/components/VideoDebate/index.jsx
app/i18n.js
app/state/index.js
app/state/video_debate/actions.js
app/state/video_debate/comments/reducer.js
app/state/video_debate/history/reducer.js
app/state/video_debate/statements/reducer.js
app/state/video_debate/statements/selectors.js
app/state/video_debate/video/reducer.js

@NGambini our conversation reminded me that tips to guide new users through the debate interface used to exist, somehow recent changes made them disappear without me noticing. They have been restored and translated (en/fr):
* Message without speakers
* Message with speakers
* `<VideoDebate/>` component was way too huge and has been split into `LeftColumn`, `RightColumn` and `StatementsList`
* Reset full VideoDebate state when unmounting
* Refactored code
* Some tricky cases are now handled (autoscroll disabled + scroll on recently added statement)
* Disable redux dev tools extension if running on prod

Restore VideoDebate tips, improve autoscroll + refactors

---

app/components/Pages/BrowserExtensionsPage.jsx
app/components/VideoDebate/History.jsx
app/components/VideoDebate/HistoryEntry.jsx
package.json

Closes #3 
* Chromium benchmarks show similar performances 
* No warnings
* No bug noticed
* Bundle size
- Size before: 1266.4Kb (GZip: 281.4Kb)
- Size after: 1212.5Kb (GZip: 271.7Kb) (-50kb / -10kb)
* New return types, including arrays and strings
* Better error handling
* [Async rendering](https://gist.github.com/acdlite/f31becd03e2f5feb9b4b22267a58bc1f)

Update to React 16

---

app/components/Comments/Source.jsx
app/components/Videos/AddVideoForm.jsx
app/components/Videos/DummyVideoPlayer.jsx
app/lib/url_utils.js
app/styles/_components/VideoDebate/video_debate.sass
app/styles/_components/comments.sass
app/styles/_components/video_player.sass
app/styles/_global/global.sass
package.json

* Using site_name to check website is not recommended. We extract it from website opengraph or <title> anchor and any website can set any value here. 
Also a website like Facebook would always be listed as a video but a Facebook links can also target posts. We need Regexp here.
* Some players have been disabled. As each one of them loads its little js bundle, it can be heavy if we have too much different players on the same page so we keep only the most popular. We may change this based on usage.
* Sounds like `preloading` option in ReactPlayer was about fixing a bug by playing video silently -not what we seek- and anyway it is already set to false by default. However, Facebook do preload (**pre-fetch is more accurate**) (part of) its content which is a no-go.
So bye bye Facebook.
* Fixed …

Sources rich medias improvements

---

config/nginx.conf
rel/run.sh

Maintenance mode is no longer released in a different docker image but instead gets embedded in all releases. To trigger maintenance mode, just set env variable `MAINTENANCE_MODE` to `ON` when deploying container / service.

Set maintenance mode by env variable

---

README.md
app/assets/assets/help/en/credits.md
app/assets/assets/help/fr/credits.md
app/assets/assets/locales/en/videoDebate.json
app/assets/assets/locales/fr/videoDebate.json
app/components/Comments/CommentDisplay.jsx
app/components/Comments/CommentForm.jsx
app/components/Comments/Source.jsx
app/components/Users/ResetPasswordConfirmForm.jsx
app/components/Users/User.jsx
app/components/UsersActions/Entity.jsx
app/constants.js
app/i18n.js
app/styles/_components/UsersActions/entity.sass
app/styles/_components/comments.sass
app/styles/_components/statements.sass
app/styles/_global/global.sass
app/styles/application.sass

* Show approve / refute for comments by changing the left border color
* Comments are more compact: less margin left, smaller pictures, and smaller sources
* Comment form:
- Align submit buttons on the same line as the source url
- Better labels for buttons if we're replying

Comments, statements and video debate history UI improvements

---

app/assets/assets/locales/en/history.json
app/assets/assets/locales/fr/history.json
app/components/UsersActions/ActionDiff.jsx
app/components/UsersActions/ActionsTable.jsx
app/components/UsersActions/EntityTitle.jsx
app/components/VideoDebate/ColumnDebate.jsx
app/components/VideoDebate/ModalHistory.jsx
app/components/VideoDebate/VideoDebateHistory.jsx
app/constants.js
app/i18n.js
app/state/user_actions/reducer.js
app/state/video_debate/history/effects.js
app/styles/_components/UsersActions/user_action.sass
app/styles/_components/VideoDebate/history.sass
app/styles/application.sass
package.json

Display history as a table and add video actions to history

---

app/components/Comments/CommentDisplay.jsx
app/components/Users/UserPicture.jsx
app/styles/_components/comments.sass
app/styles/_components/statements.sass
app/styles/_global/icons.sass

* Fix a bug with videos embedded inside comments being too large on small devices

Compact statements on mobile + small users pictures + fixes

---

app/assets/assets/locales/en/videoDebate.json
app/assets/assets/locales/fr/videoDebate.json
app/components/VideoDebate/ColumnVideo.jsx
app/components/VideoDebate/Presence.jsx
app/state/video_debate/effects.js
app/state/video_debate/presence/reducer.js
app/state/video_debate/presence/selectors.js
app/state/video_debate/reducer.js
app/styles/_components/VideoDebate/presence.sass
app/styles/_components/VideoDebate/video_debate.sass
app/styles/_components/comments.sass
app/styles/application.sass

Videodebate users / viewers live presence count

---

app/components/App/index.jsx
app/components/VideoDebate/index.jsx
package.json

Also merge changes from master

Add react-helmet to put video titlte in title tag when watching it

---

app/styles/_components/VideoDebate/video_debate.sass

Fix chat button right border

---

app/components/Comments/CommentDisplay.jsx
app/components/Users/DeleteUserModal.jsx
app/i18n/en/main.js
app/i18n/fr/main.js
app/state/video_debate/comments/record.js
app/state/video_debate/comments/selectors.js
app/styles/_components/VideoDebate/comments/comment.sass

Deleting an account is not deleting its comments anymore. Instead all user's comments are nullified.
We display `Anonymous user` instead of user's name above comment.

Allow null comment user (anonymous)

---

app/components/Speakers/SpeakerPreview.jsx
app/components/Videos/AddVideoForm.jsx
app/components/Videos/PublicVideos.jsx
app/i18n/en/main.js
app/i18n/en/videoDebate.js
app/i18n/fr/main.js
app/i18n/fr/videoDebate.js

https://trello.com/c/DawVVdvx/724-missing-translations

add missing translate

---

.eslintrc.yml
app/components/Speakers/SpeakerPage.jsx

true code : 
`SpeakerPage` set the route with given speaker's slug
linting : 
disable a rule to allow 
```Javascript 
if (predicate) 
doSomething(params)
```
instead of 
```Javascript 
if (predicate) doSomething(params)
```

Speaker Route now insensitive

---

app/components/Speakers/SpeakerPage.jsx

https://trello.com/c/vwO85slG/818-use-external-link-icon-on-speakers-page-wiki-links
Also disabled other links to Wikimedia, Wikiquotes and Wikinews as we specified previously that this was not very useful.

Use external link icon on speaker's page wiki links

---

app/styles/_components/App/sidebar.sass

Reduce username margin-bottom and fix icon width when collapsed

---

app/components/Help/Help.jsx
app/i18n/en/help.js
app/i18n/fr/help.js

These are **not** the final colors, just a fix to avoid breaking user's eyes while @raphaelecorse finish the graphical contract.

Fix help page colors and add missing translation

---

app/components/Statements/StatementHeader.jsx
app/components/VideoDebate/ColumnVideo.jsx
app/components/Videos/VideoCard.jsx
app/lib/cf_routes.js
app/state/videos/__tests__/__fixtures__/videos.json
app/state/videos/__tests__/__snapshots__/reducer.spec.js.snap
app/state/videos/record.js

Related to https://github.com/CaptainFact/captain-fact-api/pull/15

Use new video hash_id field

---

app/state/video_debate/video/__tests__/__fixtures__/fetch_all_success.json
app/state/video_debate/video/__tests__/__snapshots__/reducer.spec.js.snap
app/state/video_debate/video/__tests__/reducer.spec.js
dev/tests_setup.js

I added some snapshot test for video-debate/video/reducer. 
this is the coverage reached

Add UT for video-debate/video/reducer

---

package.json

https://github.com/CaptainFact/captain-fact/issues/68
It annoys me a bit that the prettified files are automatically included in the commit. IMHO, the process should be the same as for [`black`](https://github.com/ambv/black): if the files were edited during the hook, cancel the commit and let the user do a `git add && git commit`.

Add code formatting to pre-commit

---

app/styles/_components/VideoDebate/video_debate.sass

Resolve https://github.com/CaptainFact/captain-fact/issues/137
Only hidden with CSS so that we can still see the info in the markup if necessary.

VideoDebate: Hide presence

---

app/components/Home/Home.jsx

On the home page, the link for the backend and frontend issues is the same, which doesn't seem correct. This PR fixes this.

Fix backend issues URL

---

app/state/user_preferences/reducer.js

Addresses CaptainFact/captain-fact#140.
When the local storage doesn't contain UserPreferences, a tuple with an empty map is returned.
This tuple is then merged with the default Preferences record, which had 'en' as default rather than the browser locale.

Defaults to browser locale, when no user preferences exists.

---

package-lock.json
package.json

Reverts CaptainFact/captain-fact-frontend#695
Resolve https://github.com/CaptainFact/captain-fact/issues/150

Revert "chore(deps): bump dotenv-webpack from 1.7.0 to 3.0.0"

---

app/API/graphql_queries.js
app/components/App/Sidebar.jsx
app/styles/_components/App/sidebar.sass

Fixes CaptainFact/captain-fact#95.

Shows number of actions which are pending moderation.

---

app/components/App/Navbar.jsx
app/components/App/Sidebar.jsx
app/components/LoggedInUser/Notifications.jsx

Fix https://github.com/CaptainFact/captain-fact/issues/154
Issue was introduced by a cache conflict with the new moderation count, because the notifications query was not properly fetching the user `id`, making the cache reconciliation impossible.
Also made a small change to hide the moderation count if there's nothing to moderate or if it's loading.

Notifications: Add missing user id to the query

---

package-lock.json

Reverts CaptainFact/captain-fact-frontend#710

Revert "chore(deps): bump highlight.js from 9.15.6 to 9.18.5"

---

README.md

First of all, outstanding initiative! Congratulations to all involved :)
This is how the Main Libraries / Frameworks section is appearing right now:
This PR adds the missing `(` between the URL and the link text.

Add missing bracket & fix Phoenix Socket docs link

---

app/components/App/Sidebar.jsx

Fix an issue with the new reputation gauge that was making the menu too large when collapsed

Sidebar: Hide reputation gauge when collapsed

---

app/components/Utils/TimeSince.jsx

Fix a crash in `TimeSince` related to `date-fns` update. Should resolve the `console.log` flood issue and hopefully the crash on safari.

TimeSince: Parse time

---

app/components/Comments/CommentForm.jsx
app/i18n/en/videoDebate.json
app/i18n/fr/videoDebate.json

Suite a la remarque sur la discussion [:brain: Rejoignez la campagne de sensibilisation aux arguments fallacieux](https://forum.captainfact.io/t/rejoignez-la-campagne-de-sensibilisation-aux-arguments-fallacieux/751/6) je propose de rajouter un message qui met l'accent sur la possibilite de commettre [l'erreur sur l'erreur](https://yourlogicalfallacyis.com/fr/l-erreur-sur-l-erreur) en souhaitant signaler un argument fallacieux.
Seul les traductions francaises :fr: et anglaises :gb: ont ete realise ici.

Add message to point to the fallacy fallacy

---

app/components/Utils/TimeSince.jsx

Voir https://forum.captainfact.io/t/les-dates-et-heures-ne-sont-plus-affiches/821
Les dates n'etaient plus affiche sur les commentaires et dans l'espace utilisateur du a a l'echec de la fonction `parseISO` sur la variable `time`.
En effet cette derniere est deja une `Date` ce qui fait echoue `parseISO`.
Je n'ai pas reussit a trouver quand la variable `time` est passe d'une `String` a une `Date`.

Fix missing dates in multiple places

---

app/styles/_components/UsersActions/user_action.sass

On chrome-like engine the content of an element of class 'diff-entry' could
expand beyond its parent 'user-action card'.
Fix https://github.com/CaptainFact/captain-fact/issues/172

Prevent diff-view to expand beyond a user-action card

---

cypress/integration/video_debate/comment_form.spec.js

It seems Wikipedia updated the way they generate their `og:description`, breaking our E2E tests

Fix E2e tests Wikipedia checks

---

.dockerignore
.gitignore
app/styles/_global/variables.sass

J'ai trouvé que les liens au survol manquaient pas de mal de contraste et étaient à peine visible. 
Même si mon écran est sans doûte mal calibré je pense que ça peut améliorer la lisibilité pour d'autres que moi. 
J'ai simplement inversé le contraste de 25% plus clair à 25% plus foncé. 
Qu'en pensez-vous ?
Avant 
Après
Avant
Après
Avant
Après

Improve link contrast on hover

---

app/components/App/MenuToggleSwitch.jsx
app/components/App/Navbar.jsx

J'ai trouvé un peu déroutant que l'icône du menu ne change pas d'état quand le menu est ouvert en mobile.
En desktop j'ai laissé tel quel, l'action n'était pas la même (fermer vs réduire le menu) et avoir une croix quand on arrive sur la page si le menu est ouvert ne rend pas très bien.
Qu'en pensez-vous ?

feat(Navbar): toggle Menu icon to X icon on mobile

---

app/components/Users/UserMenu.jsx
app/router.jsx

Related issue : https://github.com/CaptainFact/captain-fact/issues/218
> Aujourd'hui, cliquer sur le pseudo d'un utilisateur mène sur son profil avec les médailles.
> Les médailles ne sont pas les infos les plus pertinentes au sujet de l'utilisateur.
> Il est proposé d'inverser "profil" (médailles) par "activité", afin que la page du profil utilisateur commence par ses activités.

update user : default display is now activity user page

---

.github/workflows/e2e.yml

Align with https://github.com/CaptainFact/captain-fact-api/pull/392 and stop relying on Docker. For https://github.com/CaptainFact/captain-fact-api/pull/399.

Remove docker from E2E CI configuration

---

app/components/Statements/Statement.jsx
app/components/Statements/StatementHeader.jsx
app/components/Statements/StatementsList.jsx
app/components/StyledUtils/Text.jsx
app/components/VideoDebate/ActionBubbleMenu.jsx
app/components/VideoDebate/CaptionsExtractor.jsx
app/components/VideoDebate/ColumnDebate.jsx
app/components/VideoDebate/ColumnVideo.jsx
app/i18n/en/main.json
app/i18n/en/videoDebate.json
app/i18n/fr/main.json
app/i18n/fr/videoDebate.json
app/lib/cf_routes.js
app/router.jsx
app/state/video_debate/statements/reducer.js
app/styles/_components/VideoDebate/action_bubble_menu.sass
package-lock.json
package.json

Require https://github.com/CaptainFact/captain-fact-api/pull/460
Implements a first version of https://github.com/CaptainFact/captain-fact/issues/53

Video Debate: Transcript section
