CaptainFact/captain-fact-frontend

.travis.yml
Also configured to push image AFTER pull request
=> Update .travis.yml to only build for master/staging/maintenance

CONTRIBUTING.md, README.md, app/API/socket_api.js, app/assets/assets/help/en/contact.md, app/assets/assets/help/en/moderation.md, app/assets/assets/help/en/privileges.md, app/assets/assets/help/en/reputation.md, app/assets/assets/help/fr/contact.md, app/assets/assets/help/fr/privileges.md, app/assets/assets/help/fr/reputation.md, app/index.html
* Improve socket disconnection
* Update docs and help pages
=>  Improve socket disconnection, update docs and help pages 

app/API/http_api.js, app/components/Comments/CommentForm.jsx, app/components/Comments/Source.jsx, app/components/Statements/StatementForm.jsx, app/components/VideoDebate/ActionBubbleMenu.jsx, app/components/Videos/VideosGrid.jsx, app/router.jsx, app/styles/_components/VideoDebate/video_debate.sass, app/styles/_components/comments.sass, package.json
* Fixes #1 
* IE 11 / Edge compatibility
* Firefox: proper scroll on statement form when adding it
=> UI / UX improvements

app/components/Pages/BrowserExtensionsPage.jsx
https://addons.mozilla.org/en-US/firefox/addon/captainfact/
=> Add link to Firefox extension 🎆

app/index.html, app/state/user_preferences/effects.js, app/styles/_components/VideoDebate/video_debate.sass, brunch-config.js, package.json
* Video ratio when resizing video column on debate
* Save user locale on server when changing it
* Add version string to assets to invalid browser cache when updating
=> Style improvement and various fixes

Dockerfile, app/assets/assets/help/en/privileges.md, app/assets/assets/help/en/reputation.md, app/assets/assets/help/fr/privileges.md, app/assets/assets/help/fr/reputation.md, app/components/Comments/Source.jsx, app/lib/url_utils.js, config/dev/env.sh, config/nginx.conf, config/prod/env.sh, config/staging/env.sh, rel/run.sh
```
Content-Security-Policy:default-src 'self'; script-src 'self' https://www.youtube.com https://s.ytimg.com; connect-src 'self' http://localhost:4000 ws://localhost:4000 https://query.wikidata.org; img-src 'self' http://localhost:4000/resources/ https://api.adorable.io https://img.youtube.com; frame-src https://www.youtube.com
Server:nginx
X-Content-Type-Options:nosniff
X-Frame-Options:DENY
X-XSS-Protection:1; mode=block
```
=> Add security headers to NGinx + remove Dailymotion / SoundCloud embed

app/components/Comments/CommentForm.jsx, app/components/Pages/BrowserExtensionsPage.jsx, app/index.html
- Collapse comment form when logging out
- Fix logo path on initial loading spinner
- Default extension browser image size
=> Pre-0.7.8 release fixes

app/components/Comments/CommentDisplay.jsx, app/components/Comments/Source.jsx, app/components/Statements/Statement.jsx, app/components/Statements/StatementForm.jsx, app/components/UsersActions/ActionsTable.jsx, app/components/VideoDebate/ColumnVideo.jsx, app/styles/_components/VideoDebate/history.sass, app/styles/_components/VideoDebate/video_debate.sass, app/styles/_components/comments.sass, app/styles/_components/statements.sass, app/styles/_global/global.sass
------------------------------------------------
Tested on Chrome, Firefox, IE, Edge and Opera
=> Comment texts in bubbles + sources and other various styling

.dockerignore, .gitignore, .travis.yml, CONTRIBUTING.md, app/index.html, app/state/user_actions/reducer.js, rel/run_dev_docker_api.sh
@NGambini this will affect your local API dev environment. You should not see any changes, but contact me if you run into issues while running `rel/run_dev_docker_api.sh`.
There's no rush for you to merge it as it have no effect on what you're currently working on.
=> Dev compatibility with API v0.8 + release on Dockerhub

app/assets/assets/help/fr/bug_report.md
Correct "divulation" to "divulgation".
=> Correct bug_report.md

app/components/Help/Help.jsx, app/components/Pages/BrowserExtensionsPage.jsx, app/components/Pages/Home.jsx, app/components/Speakers/SpeakerPage.jsx, app/components/Speakers/SpeakerPreview.jsx, app/components/Users/NewsletterSubscription.jsx, app/components/Users/User.jsx, app/components/Users/UserSettings.jsx, app/styles/_components/Pages/browser_extensions.sass, app/styles/_components/Pages/home_page.sass, app/styles/_components/Speakers/speaker_page.sass, app/styles/_components/User/user_page.sass, app/styles/_components/help.sass, app/styles/application.sass
=> Improve responsiveness on multiple pages and slightly re-style user page

app/assets/assets/help/en/contributionGuidelines.md, app/assets/assets/help/fr/ambassadors.md, app/assets/assets/help/fr/contributionGuidelines.md
Also a small fix in contribution guidelines
=> Add Ambassadors Discord link to help pages

.eslintrc.yml, app/components/App/LanguageSelector.jsx, app/components/Videos/FilterOnlyFromPartners.jsx, app/components/Videos/PublicVideos.jsx, app/i18n/en/main.js, app/i18n/fr/main.js, app/state/user_preferences/__tests__/reducer.js, app/state/user_preferences/reducer.js, app/styles/_components/Videos/index.sass, app/styles/application.sass
=> Add filter for partners videos

app/components/App/Logo.jsx, app/styles/_components/App/logo.sass
Because what matter is the Fact, not the Captain. :sunglasses:
=> Use a lighter font-weight on first part of logo

README.md, app/components/Comments/CommentsContainer.jsx, app/components/Statements/Statement.jsx, app/i18n/en/videoDebate.js, app/i18n/fr/videoDebate.js, app/state/users/record.js, app/state/video_debate/comments/reducer.js, app/state/video_debate/comments/selectors.js, app/state/video_debate/statements/selectors.js, app/styles/_components/Speakers/speaker_preview.sass, app/styles/_components/VideoDebate/comments/comments_list.sass, app/styles/_components/statements.sass
=> Self-sourcing

app/styles/_components/Speakers/speaker_preview.sass
=> Fix unwanted scrollbar on speaker's name for Windows

app/components/Statements/Statement.jsx
=> Add icons for "Community" and "Speaker" headers

config/env/dev.env, config/env/prod.env, config/env/staging.env, config/nginx.conf, rel/run.sh
- configure NGinx with new opengraph generator app
- add opengraph urls for various environments
- add opengraph application boot in run script
=> NGinx config for opengraph application

app/components/Pages/BrowserExtensionsPage.jsx
Replaced https://youtu.be/k4L0fvwsBg0 by https://youtu.be/4-_nnwgqw9c
=> Change demo video on extension page

app/assets/assets/help/en/contributionGuidelines.md, app/assets/assets/help/fr/contributionGuidelines.md
https://trello.com/c/iIKtZAvC/797-contribution-guidelines-mettre-le-au-moins-un-en-gras
=> Clarify documentation

app/constants.js
=> Increase max comment length to 512

config/nginx.conf
https://trello.com/c/y5m2FFnI/775-opengraph-add-support-for-discord-user-agent
=> Add discord bot to OpenGraph user agents

app/components/Comments/ModalFlag.jsx
=> Don's show flags limit if no limit

app/components/Videos/VideoCard.jsx, app/i18n/en/videoDebate.js, app/i18n/fr/videoDebate.js, app/styles/_components/Videos/card.sass
=> Bold text + colorful icon on partner's video cards

app/components/Users/UserFormFields.jsx
https://trello.com/c/hZTs72Oz/815-ajouter-le-type-email-sur-les-champs-email
Also refactored `UserFormFields`. We still need to separate all components in this file in independent files.
=> Af type="email" on email fields

app/styles/_components/statements.sass
Fix https://trello.com/c/0uxjQeFa/824-bug-daffichage-self-sourcing-sur-tablette
=> Fix display bug with self-sourcing on small devices

app/components/App/LanguageSelector.jsx, app/components/App/Sidebar.jsx, app/components/Users/ThirdPartyAccountLinker.jsx, app/components/Users/UserSettings.jsx, app/i18n/en/user.js, app/i18n/fr/user.js
https://trello.com/c/AckXXewq/813-am%C3%A9liorations-menu-choix-de-la-langue
Also split `ThirdPartyAccountLinker` in a separate file
=> Move LanguageSelector up in sidebar and add it to settings page

app/components/Comments/CommentAction.jsx, app/components/Comments/CommentActions.jsx, app/components/Comments/CommentDisplay.jsx, app/components/Comments/OtherCommentActions.jsx, app/styles/_components/VideoDebate/comments/comment.sass
Flagged comments were not displayed as flagged.
=> Fix flagged comment display

app/components/App/Logo.jsx
=> Import logos in JS to have them bundled

app/components/Utils/PaginationMenu.jsx, app/components/Videos/PaginatedVideosContainer.jsx, app/styles/_components/Speakers/speaker_page.sass, app/styles/_components/Videos/index.sass, app/styles/_components/Videos/videos_pagination.sass, app/styles/application.sass
=> Fix pagination broken behaviour

app/components/UsersActions/ActionEntityLink.jsx, app/components/UsersActions/ActionIcon.jsx, app/components/VideoDebate/ModalHistory.jsx, app/constants.js, app/i18n/en/history.js, app/i18n/fr/history.js, app/state/user_actions/record.js
Require https://github.com/CaptainFact/captain-fact-api/pull/36
=> User action: action type and entity as string values.

app/components/VideoDebate/VideoDebatePlayer.jsx, app/state/video_debate/video/__tests__/__snapshots__/reducer.spec.js.snap, app/state/video_debate/video/reducer.js, package.json
React-player update broke the default player behaviour with playin state.
Fix https://github.com/CaptainFact/captain-fact-frontend/issues/230
=> Fix video pauses when clicking on time-change links

app/static/assets/help/fr/contributionGuidelines.md
The result of this two works:
- https://docs.google.com/document/d/1zLoPQUatnaAHuVIxOirFgpNQ1ouHysmlf9kmUVRdTy0/edit?usp=sharing
and
- https://docs.google.com/document/d/1eoD4ZTl9c9vYhXoKPE34YIVEB5yDE2Ew6Ayu9vr_afk/edit?usp=sharing
=> Update contribution guidelines

.eslintrc.yml, app/components/Comments/CommentForm.jsx, app/components/Comments/CommentHeader.jsx, app/components/Users/UserAppellation.jsx, app/components/UsersActions/ActionsTable.jsx, app/components/Utils/CloseButton.jsx, app/i18n/en/main.js, app/i18n/en/user.js, app/i18n/fr/main.js, app/i18n/fr/user.js, app/styles/_components/User/user_appellation.sass, app/styles/_components/VideoDebate/comments/comment.sass, app/styles/_components/VideoDebate/comments/comment_form.sass
+ Replace all "anonymous user" labels by "deleted account"
+ Fix a crash when trying to reply to a comment made by a deleted user (https://github.com/CaptainFact/captain-fact/issues/8)
=>  Fix a crash when trying to reply to a comment made by a deleted user 

app/components/Statements/StatementsList.jsx, app/components/VideoDebate/VideoDebatePlayer.jsx, app/constants.js, app/index.html
- Clean index.html
- Disable statements FlipMove animations on mobile and tablet
- Improve first timecode click (when video isn't playing yet)
=> Minor improvements

.babelrc, README.md, app/components/Home/AllAmbassadors.jsx, app/components/Home/AllPartners.jsx, app/components/Home/CFSocialProfiles.jsx, app/components/Home/Home.jsx, app/components/Home/OpenCollectiveContributors.jsx, package-lock.json, package.json
Making a PR for this to reference size change in bundle. Added 4 new libraries:
- styled-components
- styled-system
- styled-icons
- @rebass/grid
Bundle size:
app.js.gz: 74kb -> 74.3kb
vendor.js.gz: 297.3kb -> 316.9kb
=> [Homepage redesign] Add social profiles icons with styled-components / styled-icons

app/components/Statements/StatementsList.jsx
See https://github.com/CaptainFact/captain-fact/issues/61
It's the first time I use React, tell me if this is fucked up.
=> Automatically fill new statement speaker if there is only one

app/components/Videos/VideoCard.jsx, app/constants.js, app/i18n/en/main.js, app/i18n/fr/main.js, app/lib/iterate_with_separators.js
https://github.com/CaptainFact/captain-fact/issues/50
=> Limit speakers list length in video card

app/components/Home/Home.jsx, app/i18n/en/home.js, app/i18n/fr/home.js
Resolve https://github.com/CaptainFact/captain-fact/issues/48
=> Try another message for the home page

app/components/App/Navbar.jsx, package-lock.json, package.json
Fix https://github.com/CaptainFact/captain-fact/issues/76
=> Fix NavBar and notifications popup responsiveness

app/components/Speakers/EditSpeakerForm.jsx, app/i18n/en/main.js, app/i18n/fr/main.js
https://github.com/CaptainFact/captain-fact/issues/55
=> Clearly display speaker title max length

app/components/Statements/StatementContainer.jsx, app/components/Statements/StatementForm.jsx
Fix When position is before provider offset and scroll behaviour
=> Improve statements scroll behaviour

config/nginx.conf
This will help to embed messages with cloudflare when needed
=> chore(nginx): Allow for inline css from data:

app/components/App/CrashReportPage.jsx, app/components/App/Layout.jsx, app/i18n/en/errors.js, app/i18n/fr/errors.js
Resolve https://github.com/CaptainFact/captain-fact/issues/46
=> Add a fallback page for unexpected errors

app/API/graphql_queries.js, app/components/App/Navbar.jsx, app/components/LoggedInUser/NotificationBell.jsx, app/components/LoggedInUser/Notifications.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/73
=> Show unread notifications count

app/components/App/Navbar.jsx, app/components/Users/ScoreTag.jsx, app/i18n/en/user.js, app/i18n/fr/user.js
Temporarily put reputation component in NavBar so users can easily see it
=> Put user reputation in NavBar

app/components/App/Navbar.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/98
=> Add notifications entry in NavBar user menu

app/static/assets/help/es/about.md, app/static/assets/help/es/achievements.md, app/static/assets/help/es/ambassadors.md, app/static/assets/help/es/bug_report.md, app/static/assets/help/es/censorship_requests.md, app/static/assets/help/es/contact.md, app/static/assets/help/es/contribute/code.md, app/static/assets/help/es/contribute/tasks.md, app/static/assets/help/es/contributionGuidelines.md, app/static/assets/help/es/credits.md, app/static/assets/help/es/extension.md, app/static/assets/help/es/jobs.md, app/static/assets/help/es/moderation.md, app/static/assets/help/es/privacy.md, app/static/assets/help/es/privileges.md, app/static/assets/help/es/reputation.md
Following up on https://github.com/CaptainFact/captain-fact-frontend/pull/536
=> Help: Add base files for spanish

app/API/graphql_api.js, app/API/http_api/index.js, app/API/socket_api.js, app/components/LoggedInUser/UserProvider.jsx, app/components/Statements/StatementForm.jsx, app/components/Utils/Message.jsx, app/components/VideoDebate/ColumnDebate.jsx, app/i18n/en/videoDebate.json, app/i18n/fr/videoDebate.json, app/lib/local_storage.js, app/state/user_preferences/reducer.js, app/styles/_components/VideoDebate/video_debate.sass
https://github.com/CaptainFact/captain-fact/issues/114
=> add video statement introduction

app/static/assets/help/en/ambassadors.md
Hi,
I translated in english this file from the french version. Hope the translation is alright and suits the project usual terms.
Cheers
=> Translation of ambassadors.md in the help directory

app/static/assets/help/es/contact.md
=> Update contact es.md

app/static/assets/help/en/contact.md
=> Update contact en.md

app/components/Speakers/SpeakerPage.jsx, app/components/Utils/DismissableMessage.jsx, app/components/Utils/Message.jsx, app/components/VideoDebate/ColumnDebate.jsx, app/components/Videos/AddVideoForm.jsx, app/i18n/en/main.json, app/i18n/fr/main.json, app/lib/local_storage.js
https://github.com/CaptainFact/captain-fact/issues/122
=> Speaker page text

app/components/App/Sidebar.jsx, app/styles/_components/App/sidebar.sass
=> Sidebar: grey social network icons

app/components/App/CrashReportPage.jsx, app/components/LoggedInUser/NotificationBell.jsx
Fix https://github.com/CaptainFact/captain-fact/issues/127
Fix https://github.com/CaptainFact/captain-fact/issues/126
Apparently broken by reactjs-popup's update in https://github.com/CaptainFact/captain-fact-frontend/pull/528
=> NotificationBell: Forward ref

app/components/Speakers/SpeakerPage.jsx
Added basic opengraph information for the speaker page too.
=> Adds opengraph information to the speaker page.

app/components/App/Logo.jsx
=> Improvement : Remove beta label in navbar

app/components/App/Logo.jsx, app/components/App/Sidebar.jsx, app/components/Speakers/SpeakerPage.jsx, app/i18n/ar/main.json, app/i18n/en/main.json, app/i18n/fr/main.json, app/styles/_global/global.sass, app/styles/_global/language_adapter.sass, package-lock.json, package.json
Icomoon is the deprecated way to add icon therefore installed @styled-icons/boostrap.
Additionally update the MenuLink internal component to allow custom dom tree.
Resolves CaptainFact/captain-fact#111.
=> Adds Contact menu to the side bar.

app/static/assets/help/ar/credits.md, app/static/assets/help/en/credits.md, app/static/assets/help/es/credits.md, app/static/assets/help/fr/credits.md, config/nginx.conf
=> Remove references to adorable.io

app/components/Users/SignupForm.jsx, app/i18n/en/user.json, app/i18n/fr/user.json
**Issue ref :** 
https://github.com/CaptainFact/captain-fact/issues/145
**Result :**
**Question**
Need translations for other languages?
=> Improvement : adding privacy policy on signup form (EN/FR)

app/components/Home/Home.jsx
issue: https://github.com/CaptainFact/captain-fact/issues/144 @mansil 
first pullrequest 🥳
=> Update home : video on french language

app/components/VideoDebate/index.jsx, app/lib/video_utils.js
Closes CaptainFact/captain-fact#141.
=> Uses HD thumbnail for opengraph when available.

app/constants.js
Part of CaptainFact/captain-fact#152
=> Set required reputation to add video to 75

app/components/Comments/CommentForm.jsx
Fix https://github.com/CaptainFact/captain-fact/issues/155
=> CommentForm: Crash when erroring

app/styles/_components/VideoDebate/video_debate.sass
Resolve https://github.com/CaptainFact/captain-fact/issues/171
=> VideoDebate/SpeakersList: Add max-height on mobile

app/components/VideoDebate/index.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/169
=> VideoDebate: Change FR page title

app/styles/_components/VideoDebate/video_debate.sass
Fix https://github.com/CaptainFact/captain-fact/issues/170
=> VideoDebate: Fix reponsiveness issue at 1280px

app/components/Notifications/NotificationDetails.jsx
Fix https://github.com/CaptainFact/captain-fact/issues/163
=> Notification: Crash on delete accounts

app/components/App/Sidebar.jsx, app/components/Home/CFSocialProfiles.jsx
https://github.com/CaptainFact/captain-fact/issues/174
=> Added mastodon icon on sidebar and social profiles section

app/components/Home/Home.jsx
https://github.com/CaptainFact/captain-fact/issues/178
=> Updated the forum link on homepage

app/components/App/Sidebar.jsx, app/components/Videos/VideosIndexPage.jsx, app/i18n/en/main.json, app/i18n/fr/main.json
Resolve https://github.com/CaptainFact/captain-fact/issues/142
=> Updated sidebar and video page title

app/components/Moderation/Moderation.jsx, app/i18n/en/moderation.json, app/i18n/fr/moderation.json, app/styles/_components/Moderation/moderation.sass
Resolve https://github.com/CaptainFact/captain-fact/issues/175
=> Added help text to moderation page

app/components/App/Navbar.jsx
https://github.com/CaptainFact/captain-fact/issues/165
For some reason ionicons set was not available, I used boxicons instead.
It is OK ? @Miragide 
https://styled-icons.js.org/?s=help
=> Added reputation help button on navbar

app/API/graphql_queries.js, app/components/App/Sidebar.jsx, app/components/Utils/ProgressBar.jsx, app/constants.js, app/i18n/en/main.json, app/i18n/fr/main.json
Resolve https://github.com/CaptainFact/captain-fact/issues/181
=> Added today reputation gain gauge to sidebar

app/components/Comments/CommentForm.jsx, app/i18n/en/videoDebate.json, app/i18n/fr/videoDebate.json
Resolve https://github.com/CaptainFact/captain-fact/issues/113
=> Added help message under comment form

app/components/Comments/CommentForm.jsx, app/components/Comments/CommentsList.jsx, app/components/Statements/StatementComments.jsx, app/i18n/en/videoDebate.json, app/i18n/fr/videoDebate.json, app/styles/_components/VideoDebate/comments/comment_form.sass
fix https://github.com/CaptainFact/captain-fact/issues/24
- You might want to do those two step in background or in two different terminal
```
docker-compose up
npm start
```
- Goes to your local instance (I used to devellop with `http://localhost:3333/videos/GoM6`)
=> Add a button to incitate to participate to debate

app/i18n/fr/videoDebate.json
=> fix(fr/videoDebate.json): typo

app/components/Home/Home.jsx, app/components/Utils/TimeSince.jsx
Related to `date-fns` update.
Also fixed a DOM nesting issue.
=> Fix crash on Safari

app/components/App/Navbar.jsx, app/components/LoggedInUser/UserProvider.jsx, app/components/SupportUs/index.jsx, app/router.jsx
Require https://github.com/opencollective/opencollective-frontend/pull/5693
The page is not yet linked in the menu, so it won't be displayed for users but we'll be able to try it ourselves by accessing the link directly.
=> Add page to embed Open Collective contribution flow

app/components/Videos/AddVideoForm.jsx, app/i18n/en/main.json, app/i18n/fr/main.json
Resolve https://github.com/CaptainFact/captain-fact/issues/166
=> Added advices for adding video

app/components/Statements/StatementForm.jsx, app/components/Utils/TimeEdit.jsx, app/styles/_components/statements.sass
Resolve https://github.com/CaptainFact/captain-fact/issues/158
https://user-images.githubusercontent.com/16321487/111180098-fcf95580-85ac-11eb-8548-0077a7fc54fd.mp4
=> Added input for editing statement's time

app/components/Videos/AddVideoForm.jsx, app/constants.js, app/i18n/en/main.json, app/i18n/fr/main.json, app/static/assets/help/ar/privileges.md, app/static/assets/help/en/privileges.md, app/static/assets/help/es/privileges.md, app/static/assets/help/fr/privileges.md
Resolve https://github.com/CaptainFact/captain-fact/issues/152
Related to : https://github.com/CaptainFact/captain-fact-api/pull/308
=> Blocked toggle in video form when a min reputation is required

app/components/Comments/FlagForm.jsx, app/components/Moderation/FlagReasonSelect.jsx, app/i18n/en/videoDebate.json, app/i18n/fr/videoDebate.json, app/static/assets/help/ar/moderation.md, app/static/assets/help/en/moderation.md, app/static/assets/help/es/moderation.md, app/static/assets/help/fr/moderation.md
Resolve https://github.com/CaptainFact/captain-fact/issues/162 without the optional comment form feature.
=> Added warning message and removed unnecessary flag reasons

app/components/Search/SearchBox.js, app/components/Search/SearchPage.js, app/components/StyledUtils/Text.jsx, app/lib/algolia.js
Fix https://github.com/CaptainFact/captain-fact/issues/188
Our quota was stressed by robots accessing the `/search` page, triggering a search with query="".
=> Search: Improve mobile and skip empty

app/components/VideoDebate/index.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/184
=> enhancement(seo): shorter meta/og titles

app/components/Statements/StatementForm.jsx, app/components/Utils/TimeEdit.jsx
Solution au deuxième problème évoqué dans ce ticket https://github.com/CaptainFact/captain-fact/issues/190
https://forum.captainfact.io/t/retours-sur-la-zone-dedition-du-time-code-des-citations/872/4
=> feat(TimeEdit): handle time icon click

package-lock.json, package.json
=> Bump Helmet to 6.1.0

app/components/Utils/FacetButton.jsx, app/components/VideoDebate/ColumnDebate.jsx, app/components/VideoDebate/ResizableColumn.jsx, app/styles/_components/VideoDebate/video_debate.sass
Fix https://github.com/CaptainFact/captain-fact/issues/203
Fix https://github.com/CaptainFact/captain-fact/issues/202
=> Responsiveness fixes & enhancements

app/components/Statements/StatementsList.jsx
Fix https://github.com/CaptainFact/captain-fact/issues/161
Fix https://github.com/CaptainFact/captain-fact/issues/112
=> VideoDebate: Fix sroll on notification click

app/components/LoggedInUser/UserProvider.jsx, app/components/Utils/ReputationGuard.jsx, app/lib/handle_effect_response.js, app/lib/url_utils.js, app/state/speakers/effects.js, app/state/video_debate/comments/__tests__/__fixtures__/fetch_all_success.js, app/static/assets/help/ar/contribute/code.md, app/static/assets/help/en/contribute/code.md, app/static/assets/help/es/contribute/code.md, app/static/assets/help/fr/contribute/code.md
API has been open-sourced for a long time, but we forgot to update the docs
=> Update contribute infos

app/components/FormUtils/ControlTextarea.jsx, app/components/Speakers/SpeakersSelect.jsx, app/components/Statements/StatementForm.jsx, app/i18n/en/videoDebate.json, app/i18n/fr/videoDebate.json, app/lib/react_select_theme.js
Resolve https://github.com/CaptainFact/captain-fact/issues/187
=> Added a warning message when submitting without speaker

app/components/Home/Home.jsx, app/i18n/fr/home.json, app/lib/local_storage.js, app/styles/_components/Pages/home_page.sass, app/styles/_global/buttons.sass, app/styles/_global/variables.sass
⚠️ This is my first open source PR: don't hesitate to tell me if I'm doing anything wrong! 
Resolve CaptainFact/captain-fact#206
Preview https://deploy-preview-868--captainfact.netlify.app/
=> 206 Update Home page with FR content

app/components/Users/User.jsx, app/components/Users/UserAppellation.jsx, app/components/VideoDebate/VideoDebateHistory.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/217
=> Add more pages to no-index

app/constants.js
Fix https://github.com/CaptainFact/captain-fact/issues/214
=> [STATEMENT] Increase max length to 280

app/components/Utils/__tests__/__snapshots__/Icon.spec.jsx.snap, app/components/Utils/__tests__/__snapshots__/ReputationGuardTooltip.spec.jsx.snap, dev/tests_setup.js, package-lock.json, package.json
Will facilitate the migration to latest node version
=> Move from enzyme to react-test-renderer

app/components/VideoDebate/index.jsx
This will fix an issue where clicking on the notification does nothing
=> Fix navigation between videos

app/components/Home/Home.jsx
Dans le but d'expliquer plus efficacement comment fonctionne CaptainFact, remplacer la vidéo actuellement sur la page d'accueil du site par celle ci : CaptainFact.io expliqué en 30 secondes https://youtu.be/BxriDuVUuMQ (vidéo non répertoriée actuellement)
L'ancienne vidéo reste accessible sur le site de la commu FR https://fr.captainfact.io/
=> shorter video

app/static/assets/help/ar/extension.md, app/static/assets/help/en/extension.md, app/static/assets/help/es/extension.md
Goes with https://github.com/CaptainFact/captain-fact-extension/pull/190
=> docs(Extension): remove tabs permission

app/components/Speakers/SpeakerPage.jsx, app/components/Videos/PaginatedVideosContainer.jsx
Resolve https://github.com/CaptainFact/captain-fact/issues/220
=> Speaker Page: improve Links & SEO

app/i18n/ru/main.json
=> Shorter translation for factchecking (RU)

app/static/assets/help/en/moderation.md, app/static/assets/help/fr/moderation.md
Modifications to moderation help page to add a section about video moderation according to issue 233.
=> Nevjoia video moderation

.github/workflows/ci.yml, app/components/LoggedInUser/Notifications.jsx, app/components/Notifications/SubscribeBtn.jsx, app/components/SupportUs/index.jsx, app/components/VideoDebate/ActionBubbleMenu.jsx, app/components/Videos/EditVideoModal.jsx
Goes with https://github.com/CaptainFact/captain-fact-api/pull/483
=> Misc styles & GraphQL fixes
